#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES :=

# header files in this project
HEADERS :=	l3g4200.hpp i2c_fast.hpp slave.hpp

# set RELATIVE to the next higher directory 
RELATIVE := ..

# other places to look for files for this project
SEARCH  := $(RELATIVE)/Sogyrolib/Slave


# and defer to the appropriate Makefile.* there

include $(RELATIVE)/Makefile.uno
